### ISSUE TITLE
Adding Firefox files

### ISSUE THREAD

**Issue by channy** [mozillakr/mozilla.or.kr#9]
Firefox 폴더 콘텐츠를 추가합니다. 여기에 몇 가지 기능 개선이 필요합니다. 

1. Firefox용 헤더가 별도로 있으므로 추가 
	include $_SERVER["DOCUMENT_ROOT"]."/ko/includes/header-fx.php";

2. 다운로드 링크에 대한 정보 추가. 
	include $_SERVER["DOCUMENT_ROOT"]."/ko/includes/download.php";
    다운로드는 크게 4가지 버튼이 있습니다. 
   1) 모바일용:      small or large    <?=download_button_mobile("small")?> 
   2) 데스크톱용:   small or large    <?=download_button_mobile("small", $fx_version)?>

**Comment by hyeonseok** [comment]
사이트 내용 변경으로 더이상 유효하지 않습니다.
